######################################################################
# Automatically generated by qmake (3.0) Sun Oct 18 11:50:36 2020
######################################################################

TEMPLATE = app
TARGET = qt_test
INCLUDEPATH += .

# Input
SOURCES += test.cpp
HEADERS += test.h
QT += widgets
QT += multimedia
QT += opengl
