######################################################################
# Automatically generated by qmake (3.0) Mon Nov 2 20:04:17 2020
######################################################################

TEMPLATE = app
TARGET = qtopengl
INCLUDEPATH += .

# Input
HEADERS += test.h
SOURCES += main.cpp test.cpp

QT += opengl
RESOURCES += qtopengl.qrc
